application: web-battle
version: 7 
runtime: python27
api_version: 1
threadsafe: true 

handlers:

- url: /css
  static_dir: webbattle/css

- url: /img
  static_dir: webbattle/img

- url: .*
  script: main.app
